CREATE TABLE ENFERMEIRO (
ID_ENFERMEIRO INT NOT NULL IDENTITY ,
NOME_ENFERMEIRO VARCHAR(50) ,
COREN_ENFERMEIRO VARCHAR(14) ,
PRIMARY KEY(ID_ENFERMEIRO));
CREATE TABLE CIDADE (
ID_CIDADE INT NOT NULL IDENTITY ,
NOME_CIDADE VARCHAR(50) ,
UF_CIDADE CHAR(2) ,
PRIMARY KEY(ID_CIDADE));
CREATE TABLE VACINA (
ID_VACINA INT NOT NULL IDENTITY,
NOME_VACINA VARCHAR(50) ,
DATANASC_VACINA DATE ,
END_VACINA VARCHAR(100) ,
CIDADE_ID_CIDADE INT NOT NULL ,
CPF_VACINA CHAR(11) ,
RG_VACINA CHAR(9) ,
DATA_VACINA DATE ,
TIPO_VACINA CHAR(1) ,
COMORBIDADE_VACINA CHAR(1) ,
GRUPOPRIORI_VACINA CHAR(1) ,
ENFERMEIRO_ID_ENFERMEIRO INT NOT NULL ,
PRIMARY KEY(ID_VACINA) ,
FOREIGN KEY(CIDADE_ID_CIDADE)
REFERENCES CIDADE(ID_CIDADE),
FOREIGN KEY(ENFERMEIRO_ID_ENFERMEIRO)
REFERENCES ENFERMEIRO(ID_ENFERMEIRO));